- name: Build and push Docker image
  uses: docker/build-push-action@v1.1.0
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
    repository: latenssi/chorer
    tags: test
    dockerfile: docker/Dockerfile
